#!/bin/bash
#set -xv

trap "sudo /usr/local/bin/bright ; setterm --term linux --cursor on ; setterm -term linux --blank 1 ; setterm --term linux --blank=poke ; exit" 2

setterm --term linux --blank=force
sudo /usr/local/bin/dim
while :
do
  curl https://api.tfl.gov.uk/Line/district,northern,piccadilly,central/Disruption 2> /dev/null | jq -r '.[] | .description' > /tmp/tubestatus.out
  
  if [ -s /tmp/tubestatus.out ]
  then
    setterm --term linux --blank=poke
    setterm --term linux --blank 0
    setterm --term linux --cursor off
    printf "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    cat /tmp/tubestatus.out | sort -u | while read line rest
    do
      case "$line" in
        Piccadilly|piccadilly)	fg=white; bg=blue;;
        Central|central)	fg=white; bg=red;;
        Northern|northern)	fg=black; bg=white;;
        District|district)	fg=black; bg=green;;
        *)			fg=white; bg=black;;
      esac
      setterm --term linux --background=$bg --foreground=$fg
      echo ""
      echo "$line $rest"
      setterm --term linux --background=black --foreground=white
    done
    i=1
    while [ "$i" -lt "29" ]
    do
      echo ""
      sleep 2
      i=$((i+1))
    done
  else
    setterm --term linux --blank 1
    setterm --term linux --cursor on
    sleep 30
  fi
done
